import './globals.css'
import type { Metadata } from 'next'
import { Nunito, Nunito_Sans } from 'next/font/google'
import clsx from 'clsx'

const nunito = Nunito({
  subsets: ['latin'],
  variable: "--font-nunito",
  display: 'swap',
});

const nunito_sans = Nunito_Sans({
  subsets: ['latin'],
  variable: "--font-nunito-san",
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={clsx(nunito.variable, nunito_sans.variable)} lang="en">
      <body >{children}</body>
    </html>
  )
}
